http://localhost:5000/mohans
X-API-KEY: wh2j4gj32rbwvhj324gfhj32v4j3v2hj4g3h53g2hh3424hgg3jb42khv32j4vj32v43hjp34y2fv432kc


####
http://localhost:5000/seed
X-API-KEY: wh2j4gj32rbwvhj324gfhj32v4j3v2hj4g3h53g2hh3424hgg3jb42khv32j4vj32v43hjp34y2fv432kc

# content-type: application/json


####
POST http://localhost:5000/mohan HTTP/1.1
X-API-KEY: wh2j4gj32rbwvhj324gfhj32v4j3v2hj4g3h53g2hh3424hgg3jb42khv32j4vj32v43hjp34y2fv432kc
content-type: application/json

{
    "title": "test3",
    "content": "test3",
    "status": 1,
    "type": "main_content"
}

####
http://localhost:5000/mohans/main_content/1
X-API-KEY: wh2j4gj32rbwvhj324gfhj32v4j3v2hj4g3h53g2hh3424hgg3jb42khv32j4vj32v43hjp34y2fv432kc

# content-type: application/json

####

PUT http://localhost:5000/mohan HTTP/1.1
X-API-KEY: wh2j4gj32rbwvhj324gfhj32v4j3v2hj4g3h53g2hh3424hgg3jb42khv32j4vj32v43hjp34y2fv432kc
content-type: application/json

{   "id": 3,
    "title": "test3",
    "content": "test3",
    "status": 0,
    "type": "main_content"
}

####